name = "Visual Studio Code"


[[check_procedures]]
type = "command_exists"
command = "code"


[[enabling_procedures]]
id = "user_config_theme"

[[enabling_procedures.requires]]
id = "theme_name"
type = "string"

[enabling_procedures.function]
type = "json_entry"
file = "~/.config/Code/User/settings.json"
entry = [
    "workbench.colorTheme"
]
value = "@theme_name"