[id]
desktop_entry = "/usr/share/applications/code.desktop"
name = "Visual Studio Code"


[[installation_check]]
type = "which"
command = "code"


[[enabling_procedures]]
id = "user_config_theme"

[[enabling_procedures.requires]]
id = "theme_name"
type = "string"

[enabling_procedures.function]
type = "json_entry"
file = "~/.config/Code/User/settings.json"
json_entry = [
    "workbench.colorTheme"
]
value = "@theme_name"