[id]
desktop_entry = false
name = "Xresources"


[[installation_check]]
type = "which"
command = "xrdb"


[[enabling_procedures]]
id = "replace"

[[enabling_procedures.requires]]
id = "file"
type = "path"

[enabling_procedures.function]
type = "shell"
command = "xrdb"
args = [
    "@file"
]


[[enabling_procedures]]
id = "merge"

[[enabling_procedures.requires]]
id = "file"
type = "path"

[enabling_procedures.function]
type = "shell"
command = "xrdb"
args = [
    "-merge",
    "@file"
]


[[enabling_procedures]]
id = "symlink"

[[enabling_procedures.requires]]
id = "target"
type = "path"

[[enabling_procedures.requires]]
id = "source"
type = "path"

[enabling_procedures.function]
type = "create_symlink"
source = "@source"
target = "@target"